/*jshint maxlen:false */

define({
    ACTION:                             "Action",
    ADD_ENDLINE_TO_THE_END_OF_FILE:     "Add endline at the end of file",
    ADD_TO_GITIGNORE:                   "Add to .gitignore",
    AMEND_COMMIT:                       "Amend last commit",
    AMEND_COMMIT_FORBIDDEN:             "Cannot amend commit when there are no unpushed commits",
    _ANOTHER_BRANCH:                    "another branch",
    AUTHOR:                             "Author",
    AUTHORS_OF:                         "Authors of",
    BASIC_CONFIGURATION:                "Basic configuration",
    BRACKETS_GIT_ERROR:                 "Git encountered an error\u2026",
    BRANCH_NAME:                        "Branch name",
    BUTTON_CANCEL:                      "Cancel",
    BUTTON_CHECKOUT_COMMIT:             "Checkout",
    CHECKOUT_COMMIT:                    "Checkout",
    CHECKOUT_COMMIT_DETAIL:             "<b>Commit Message:</b> {0} <br><b>Commit hash:</b> {1}",
    BUTTON_CLONE:                       "Clone",
    BUTTON_CLOSE:                       "Close",
    BUTTON_COMMIT:                      "Commit",
    BUTTON_DEFAULTS:                    "Restore defaults",
    BUTTON_FIND_CONFLICTS:              "Find conflicts\u2026",
    BUTTON_INIT:                        "Init",
    BUTTON_MERGE_ABORT:                 "Abort merge",
    BUTTON_OK:                          "OK",
    BUTTON_REBASE_ABORT:                "Abort",
    BUTTON_REBASE_CONTINUE:             "Continue rebase",
    BUTTON_REBASE_SKIP:                 "Skip",
    MENU_RESET_HARD:                    "Discard changes and commits after this (hard reset)",
    MENU_RESET_MIXED:                   "Discard commits after this but keep changes unstaged (mixed reset)",
    MENU_RESET_SOFT:                    "Discard commits after this but keep changes staged (soft reset)",
    RESET_HARD_TITLE:                   "Confirm Hard Reset",
    RESET_MIXED_TITLE:                  "Confirm Mixed Reset",
    RESET_SOFT_TITLE:                   "Confirm Soft Reset",
    RESET_DETAIL:                       "<b>Commits after the following will be discarded:</b><br><b>Commit Message:</b> {0}<br><b>Git Command:</b> {1}",
    RESET_HARD_MESSAGE:                 "This action will discard all changes and commits after the selected commit. <b>This operation cannot be undone easily.</b> Are you sure you want to proceed?",
    RESET_MIXED_MESSAGE:                "This action will discard all commits after the selected commit but keep all changes unstaged. <b>This operation cannot be undone easily.</b> Are you sure you want to proceed?",
    RESET_SOFT_MESSAGE:                 "This action will discard all commits after the selected commit but keep all changes staged for a new commit. <b>This operation cannot be undone easily.</b> Are you sure you want to proceed?",
    BUTTON_SAVE:                        "Save",
    RESET:                              "Reset",
    CANCEL:                             "Cancel",
    CHANGE_USER_EMAIL:                  "Change git email",
    CHANGE_USER_NAME:                   "Change git username",
    CHECK_GIT_SETTINGS:                 "Failed to launch Git executable - is Git installed? fix Git settings and restart app",
    CLEAN_FILE_END:                     "File cleaned",
    CLEAN_FILE_START:                   "Cleaning file",
    CLEANING_WHITESPACE_PROGRESS:       "Cleaning whitespace from files\u2026",
    CLEAR_WHITESPACE_ON_FILE_SAVE:      "Clear whitespace on file save",
    CLONE_REPOSITORY:                   "Clone repository",
    CODE_INSPECTION_PROBLEMS:           "Code inspection problems:",
    COLLAPSE_ALL:                       "Collapse all",
    COMMIT:                             "Commit",
    COMMIT_ALL_SHORTCUT:                "Commit all files",
    COMMIT_CURRENT_SHORTCUT:            "Commit current file",
    COMMIT_MESSAGE_PLACEHOLDER:         "Enter commit message here\u2026",
    CREATE_NEW_BRANCH:                  "Create new branch\u2026",
    CREATE_NEW_GITFTP_SCOPE:            "Create new Git-FTP remote\u2026",
    CREATE_NEW_REMOTE:                  "Create new remote\u2026",
    CURRENT_TRACKING_BRANCH:            "Current tracking branch",
    _CURRENT_TRACKING_BRANCH:           "current tracking branch",
    DEFAULT_GIT_TIMEOUT:                "Default Git operation timeout (in seconds)",
    DELETE_FILE:                        "Delete file",
    DELETE_LOCAL_BRANCH:                "Delete local branch",
    DELETE_LOCAL_BRANCH_NAME:           "Do you really wish to delete local branch \"{0}\"?",
    DELETE_REMOTE:                      "Delete remote",
    DELETE_REMOTE_NAME:                 "Do you really wish to delete remote \"{0}\"?",
    DELETE_SCOPE:                       "Delete Git-FTP scope",
    DELETE_SCOPE_NAME:                  "Do you really wish to delete Git-FTP scope \"{0}\"?",
    DIALOG_CHECKOUT:                    "When checking out a commit, the repo will go into a DETACHED HEAD state. You can't make any commits unless you create a branch based on this.",
    DIALOG_PULL_TITLE:                  "Pull from remote",
    DIALOG_PUSH_TITLE:                  "Push to remote",
    DIFF:                               "Diff",
    DIFFTOOL:                           "Diff with difftool",
    DIFF_FAILED_SEE_FILES:              "Git diff failed to provide diff results. This is the list of staged files to be commited:",
    DIFF_TOO_LONG:                      "Diff too long to display",
    ENABLE_GERRIT_PUSH_REF:             "Use Gerrit-compatible push ref",
    ENTER_GITFTP_SCOPE_NAME:            "Enter name of the new Git-FTP remote:",
    ENTER_GITFTP_SCOPE_URL:             "Enter FTP URL of the new Git-FTP remote specifing username and password:",
    ENTER_NEW_USER_EMAIL:               "Enter email",
    ENTER_NEW_USER_NAME:                "Enter username",
    ENTER_PASSWORD:                     "Enter password:",
    ENTER_REMOTE_GIT_URL:               "Enter Git URL of the repository you want to clone:",
    ENTER_REMOTE_NAME:                  "Enter name of the new remote:",
    ENTER_REMOTE_URL:                   "Enter URL of the new remote:",
    ENTER_USERNAME:                     "Enter username:",
    ERROR_NOTHING_SELECTED:             "Nothing is selected!",
    ERROR_SAVE_FIRST:                   "Save the document first!",
    ERROR_TERMINAL_NOT_FOUND:           "Terminal was not found for your OS, you can define a custom Terminal command in the settings",
    EXPAND_ALL:                         "Expand all",
    EXTENDED_COMMIT_MESSAGE:            "EXTENDED",
    FEATURES:                           "Features",
    FILE_ADDED:                         "New file",
    FILE_COPIED:                        "Copied",
    FILE_DELETED:                       "Deleted",
    FILE_IGNORED:                       "Ignored",
    FILE_MODIFIED:                      "Modified",
    FILE_RENAMED:                       "Renamed",
    FILE_STAGED:                        "Staged",
    FILE_UNMERGED:                      "Unmerged",
    FILE_UNMODIFIED:                    "Unmodified",
    FILE_UNTRACKED:                     "Untracked",
    FOR_MAC_LINUX_USERS:                "For Mac/Linux users",
    FOR_WINDOWS_USERS:                  "For Windows users",
    GETTING_STAGED_DIFF_PROGRESS:       "Getting diff of staged files\u2026",
    GITFTP_PUSH_RESPONSE:               "Git-FTP Push response",
    GITFTP_SCOPES:                      "Git-FTP remotes",
    GIT_COMMIT:                         "Git commit\u2026",
    GIT_CONFIGURATION:                  "Git configuration",
    GIT_DIFF:                           "Git diff &mdash;",
    GIT_PULL_RESPONSE:                  "Git Pull response",
    GIT_PUSH_RESPONSE:                  "Git Push response",
    GIT_REMOTES:                        "Git remotes",
    GIT_SETTINGS:                       "Git Settings\u2026",
    GOTO_NEXT_GIT_CHANGE:               "Go to next Git change",
    GOTO_PREVIOUS_GIT_CHANGE:           "Go to previous Git change",
    GUTTER_CLICK_DETAILS:               "Click for more details",
    HIDE_UNTRACKED:                     "Hide untracked",
    HISTORY:                            "History",
    HISTORY_COMMIT_BY:                  "by",
    INIT_GITFTP_SCOPE:                  "Initialize Git-FTP remote",
    INIT_GITFTP_SCOPE_NAME:             "Initialize Git-FTP remote \"{0}\"?",
    LINES:                              "Lines",
    _LINES:                             "lines",
    LIST_MODIFIED_FILES:                "Modified files",
    LOADING:                            "Loading\u2026",
    MARK_MODIFIED_FILES_IN_TREE:        "Mark modified files in file tree",
    MERGE_BRANCH:                       "Merge branch",
    MERGE_MESSAGE:                      "Merge message",
    MERGE_RESULT:                       "Merge result",
    MORE_INFO:                          "More information\u2026",
    NORMALIZE_LINE_ENDINGS:             "Normalize line endings (to \\n)",
    NOTHING_TO_COMMIT:                  "Nothing to commit, working directory clean.",
    OK:                                 "OK",
    OPERATION_IN_PROGRESS_TITLE:        "Git operation in progress\u2026",
    ORIGIN_BRANCH:                      "Origin branch",
    ON_BRANCH:                          "'{0}' - Current Git branch",
    PANEL_COMMAND:                      "Show Git panel",
    PASSWORD:                           "Password",
    PASSWORDS:                          "Passwords",
    PATH_TO_GIT_EXECUTABLE:             "Path to Git executable",
    PATH_TO_GIT_MSYSGIT:                "Path to msysgit folder",
    PULL_AVOID_MERGING:                 "Avoid manual merging",
    PULL_DEFAULT:                       "Default merge",
    PULL_FROM:                          "Pull from",
    PULL_MERGE_NOCOMMIT:                "Merge without commit",
    PULL_REBASE:                        "Use rebase",
    PULL_RESET:                         "Use soft reset",
    PULL_SHORTCUT:                      "Pull from remote",
    PUSH_DEFAULT:                       "Default push",
    PUSH_DELETE_BRANCH:                 "Delete remote branch",
    PUSH_SEND_TAGS:                     "Send tags",
    PUSH_FORCED:                        "Forced push",
    PUSH_SHORTCUT:                      "Push to remote",
    PUSH_TO:                            "Push to",
    Q_DELETE_FILE:                      "Are you sure you wish to delete the file <span class='dialog-filename'>{0}</span>?",
    Q_RESTART_BRACKETS:                 "Do you wish to restart {APP_NAME} to apply new settings?",
    Q_UNDO_CHANGES:                     "Reset changes to file <span class='dialog-filename'>{0}</span>?",
    REBASE_RESULT:                      "Rebase result",
    REFRESH_GIT:                        "Refresh Git",
    REMOVE_BOM:                         "Remove BOM from files",
    REMOVE_FROM_GITIGNORE:              "Remove from .gitignore",
    RESET_LOCAL_REPO:                   "Discard all changes since last commit",
    RESET_LOCAL_REPO_CONFIRM:           "Do you wish to discard all changes done since last commit? This action can't be reverted.",
    RESTART:                            "Restart",
    SAVE_CREDENTIALS_HELP:              "You don't need to fill out username/password if your credentials are managed elsewhere. Use this only when your operation keeps timing out.",
    SAVE_CREDENTIALS_IN_URL:            "Save credentials to remote url (in plain text)",
    SAVE_PASSWORD_QUESTION:             "Save username/password?",
    SET_ORIGIN_URL:                     "Set origin URL",
    SET_THIS_BRANCH_AS_TRACKING:        "Set this branch as a new tracking branch",
    SHOW_UNTRACKED:                     "Show untracked",
    STRIP_WHITESPACE_FROM_COMMITS:      "Strip trailing whitespace from commits",
    TARGET_BRANCH:                      "Target branch",
    TITLE_CHECKOUT:                     "Checkout Commit?",
    TOOLTIP_CHECKOUT_COMMIT:            "Checkout a specific commit",
    TOOLTIP_CLONE:                      "Clone existing repository",
    TOOLTIP_COMMIT:                     "Commit the selected files",
    TOOLTIP_FETCH:                      "Fetch all remotes and refresh counters",
    TOOLTIP_FIND_CONFLICTS:             "Starts a search for Git merge/rebase conflicts in the project",
    TOOLTIP_GITPUSH:                    "Git-FTP Push",
    TOOLTIP_HIDE_FILE_HISTORY:          "Hide file history",
    TOOLTIP_HIDE_HISTORY:               "Hide history",
    TOOLTIP_INIT:                       "Initialize repository",
    TOOLTIP_MERGE_ABORT:                "Abort the merge operation and reset HEAD to the last local commit",
    TOOLTIP_MORE:                       "More actions\u2026",
    TOOLTIP_PICK_REMOTE:                "Pick preferred remote",
    TOOLTIP_PULL:                       "Git Pull",
    TOOLTIP_PUSH:                       "Git Push",
    TOOLTIP_REBASE_ABORT:               "Abort the rebase operation and reset HEAD to the original branch",
    TOOLTIP_REBASE_CONTINUE:            "Restart the rebasing process after having resolved a merge conflict",
    TOOLTIP_REBASE_SKIP:                "Restart the rebasing process by skipping the current patch",
    TOOLTIP_REFRESH_PANEL:              "Refresh panel",
    TOOLTIP_SHOW_FILE_HISTORY:          "Show file history",
    TOOLTIP_SHOW_HISTORY:               "Show history",
    UNDO_CHANGES:                       "Discard changes",
    UNDO_LAST_LOCAL_COMMIT:             "Undo last local (not pushed) commit",
    URL:                                "URL",
    USERNAME:                           "Username",
    USER_ABORTED:                       "User aborted!",
    USE_CODE_INSPECTION:                "Use Code inspection",
    USE_GIT_GUTTER:                     "Use Git gutter marks",
    USE_NOFF:                           "Create a merge commit even when the merge resolves as a fast-forward (--no-ff)",
    USE_REBASE:                         "Use REBASE",
    USE_VERBOSE_DIFF:                   "Show verbose output in diffs",
    USE_DIFFTOOL:                       "Use difftool for diffs",
    USING_GIT_VERSION:                  "Git version",
    VIEW_AUTHORS_FILE:                  "View authors of file",
    VIEW_AUTHORS_SELECTION:             "View authors of selection",
    VIEW_THIS_FILE:                     "View this file",
    TAG_NAME_PLACEHOLDER:               "Enter tag name here\u2026",
    TAG_NAME:                           "Tag",
    CMD_CLOSE_UNMODIFIED:               "Close Unmodified Files"
});
